-- Bus Ticketing System Oracle Database Setup
-- Run this in Oracle SQL Developer or SQL*Plus

-- Drop existing tables (if they exist) using PL/SQL blocks to avoid "table does not exist" errors
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "Reviews" CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "Bookings" CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "Buses" CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "Notices" CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "Users" CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Create Users table
CREATE TABLE "Users" (
    "Id" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" VARCHAR2(100) NOT NULL,
    "Username" VARCHAR2(50) NOT NULL UNIQUE,
    "Email" VARCHAR2(100) NOT NULL UNIQUE,
    "Password" VARCHAR2(255) NOT NULL,
    "Phone" VARCHAR2(20),
    "PermanentDistrict" VARCHAR2(100) DEFAULT '' NOT NULL,
    "PresArea" VARCHAR2(100) DEFAULT '' NOT NULL,
    "PresUpazilla" VARCHAR2(100) DEFAULT '' NOT NULL,
    "PresDistrict" VARCHAR2(100) DEFAULT '' NOT NULL,
    "PresDivision" VARCHAR2(100) DEFAULT '' NOT NULL,
    "PermArea" VARCHAR2(100) DEFAULT '' NOT NULL,
    "PermUpazilla" VARCHAR2(100) DEFAULT '' NOT NULL,
    "PermDivision" VARCHAR2(100) DEFAULT '' NOT NULL,
    "Gender" VARCHAR2(20) DEFAULT '' NOT NULL,
    "Profession" VARCHAR2(100) DEFAULT '' NOT NULL,
    "Role" VARCHAR2(50) DEFAULT 'User' NOT NULL,
    "CreatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Create Notices table
CREATE TABLE "Notices" (
    "Id" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "NoticeNumber" VARCHAR2(10) NOT NULL,
    "Title" VARCHAR2(100) NOT NULL,
    "Content" CLOB NOT NULL,
    "CreatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Create Buses table
CREATE TABLE "Buses" (
    "Id" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Operator" VARCHAR2(100) NOT NULL,
    "BusType" VARCHAR2(50) NOT NULL,
    "DepartureTime" VARCHAR2(50) NOT NULL,
    "Fare" NUMBER(10) NOT NULL,
    "AvailableSeats" NUMBER(10) NOT NULL,
    "FromDistrict" VARCHAR2(100) NOT NULL,
    "ToDistrict" VARCHAR2(100) NOT NULL,
    "JourneyDate" VARCHAR2(50) DEFAULT '' NOT NULL,
    "BookedSeats" VARCHAR2(500) DEFAULT '' NOT NULL
);

-- Create Bookings table
CREATE TABLE "Bookings" (
    "Id" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserEmail" VARCHAR2(100) NOT NULL,
    "BusId" NUMBER(10) NOT NULL,
    "BusName" VARCHAR2(100) NOT NULL,
    "FromDistrict" VARCHAR2(100) NOT NULL,
    "ToDistrict" VARCHAR2(100) NOT NULL,
    "JourneyDate" VARCHAR2(50) NOT NULL,
    "Seats" VARCHAR2(100) NOT NULL,
    "PaymentMethod" VARCHAR2(50) NOT NULL,
    "TicketIssuingTime" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "DepartureTime" VARCHAR2(50) DEFAULT '' NOT NULL,
    "Status" VARCHAR2(50) DEFAULT 'Upcoming' NOT NULL
);

-- Create Reviews table
CREATE TABLE "Reviews" (
    "Id" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "BookingId" NUMBER(10) NOT NULL,
    "UserEmail" VARCHAR2(100) NOT NULL,
    "BusOperator" VARCHAR2(100) NOT NULL,
    "Route" VARCHAR2(200) NOT NULL,
    "JourneyDate" VARCHAR2(50) NOT NULL,
    "Rating" NUMBER(10) NOT NULL,
    "Comment" VARCHAR2(1000) NOT NULL,
    "CreatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Create index on Buses table (for fast search)
CREATE INDEX "IX_Buses_FromTo" ON "Buses" ("FromDistrict", "ToDistrict");

-- Seed default notices matching system requirements
INSERT INTO "Notices" ("NoticeNumber", "Title", "Content") VALUES 
('01', 'Refund Policy', 'Eid tickets are non-cancellable, non-transferable, and non-refundable, except where a refund is approved under the applicable refund policy due to operator-cancelled trips.');

INSERT INTO "Notices" ("NoticeNumber", "Title", "Content") VALUES 
('02', 'Eid Period', 'As per Bangladesh Bus Owners Association''s declaration, the Eid trip period will be from 14 May 2026 to 13 June 2026.');

INSERT INTO "Notices" ("NoticeNumber", "Title", "Content") VALUES 
('03', 'Operator Rights', 'Bus operators reserve the right to delay, cancel, reschedule, change bus type, change seats, change routes, or change boarding points due to unavoidable operational reasons.');

INSERT INTO "Notices" ("NoticeNumber", "Title", "Content") VALUES 
('04', 'Reporting Time', 'Passengers must report to the correct boarding point at least 30 minutes before the scheduled departure time. Travello will not be responsible for missed trips, cancellation, rescheduling, or seat reassignment due to late reporting.');

INSERT INTO "Notices" ("NoticeNumber", "Title", "Content") VALUES 
('05', 'Refund Processing', 'If a trip is cancelled by the bus operator and refund is approved, the refundable amount will be credited to the original payment method, bank card or MFS number used for the purchase, within a reasonable timeframe and subject to payment partner policies.');

COMMIT;
