-- Bus Ticketing System Oracle Database Setup (Oracle 11g / 12c / 19c+ Compatible)
-- Run this in Oracle SQL Developer or SQL*Plus

-- Force connection schema context to SYSTEM to ensure tables are created in the right schema
ALTER SESSION SET CURRENT_SCHEMA = SYSTEM;

-- Drop existing tables and sequences (drop both mixed-case and uppercase versions to be clean)
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "REVIEWS" CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "Reviews" CASCADE CONCONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "Reviews" CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "BOOKINGS" CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "Bookings" CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "BUSES" CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "Buses" CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "NOTICES" CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "Notices" CASCADE CONCONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "Notices" CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "USERS" CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "Users" CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE "USERS_SEQ"';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE "Users_Seq"';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE "NOTICES_SEQ"';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE "Notices_Seq"';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE "BUSES_SEQ"';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE "Buses_Seq"';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE "BOOKINGS_SEQ"';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE "Bookings_Seq"';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE "REVIEWS_SEQ"';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE "Reviews_Seq"';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Create sequences for IDs (EF Core HiLo expects these sequences)
CREATE SEQUENCE "USERS_SEQ" START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE "NOTICES_SEQ" START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE "BUSES_SEQ" START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE "BOOKINGS_SEQ" START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE "REVIEWS_SEQ" START WITH 1 INCREMENT BY 1;

-- Create USERS table (all uppercase fields)
CREATE TABLE "USERS" (
    "ID" NUMBER PRIMARY KEY,
    "NAME" VARCHAR2(100) NOT NULL,
    "USERNAME" VARCHAR2(50) NOT NULL UNIQUE,
    "EMAIL" VARCHAR2(100) NOT NULL UNIQUE,
    "PASSWORD" VARCHAR2(255) NOT NULL,
    "PHONE" VARCHAR2(20),
    "PERMANENTDISTRICT" VARCHAR2(100) DEFAULT NULL,
    "PRESAREA" VARCHAR2(100) DEFAULT NULL,
    "PRESUPAZILLA" VARCHAR2(100) DEFAULT NULL,
    "PRESDISTRICT" VARCHAR2(100) DEFAULT NULL,
    "PRESDIVISION" VARCHAR2(100) DEFAULT NULL,
    "PERMAREA" VARCHAR2(100) DEFAULT NULL,
    "PERMUPAZILLA" VARCHAR2(100) DEFAULT NULL,
    "PERMDIVISION" VARCHAR2(100) DEFAULT NULL,
    "GENDER" VARCHAR2(20) DEFAULT NULL,
    "PROFESSION" VARCHAR2(100) DEFAULT NULL,
    "ROLE" VARCHAR2(50) DEFAULT 'User' NOT NULL,
    "CREATEDAT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Trigger to auto-generate IDs for insert statements
CREATE OR REPLACE TRIGGER "USERS_TRG"
BEFORE INSERT ON "USERS"
FOR EACH ROW
BEGIN
  IF :new."ID" IS NULL THEN
    SELECT "USERS_SEQ".NEXTVAL INTO :new."ID" FROM DUAL;
  END IF;
END;
/

-- Create NOTICES table
CREATE TABLE "NOTICES" (
    "ID" NUMBER PRIMARY KEY,
    "NOTICENUMBER" VARCHAR2(10) NOT NULL,
    "TITLE" VARCHAR2(100) NOT NULL,
    "CONTENT" CLOB NOT NULL,
    "CREATEDAT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE OR REPLACE TRIGGER "NOTICES_TRG"
BEFORE INSERT ON "NOTICES"
FOR EACH ROW
BEGIN
  IF :new."ID" IS NULL THEN
    SELECT "NOTICES_SEQ".NEXTVAL INTO :new."ID" FROM DUAL;
  END IF;
END;
/

-- Create BUSES table
CREATE TABLE "BUSES" (
    "ID" NUMBER PRIMARY KEY,
    "OPERATOR" VARCHAR2(100) NOT NULL,
    "BUSTYPE" VARCHAR2(50) NOT NULL,
    "DEPARTURETIME" VARCHAR2(50) NOT NULL,
    "FARE" NUMBER(10) NOT NULL,
    "AVAILABLESEATS" NUMBER(10) NOT NULL,
    "FROMDISTRICT" VARCHAR2(100) NOT NULL,
    "TODISTRICT" VARCHAR2(100) NOT NULL,
    "JOURNEYDATE" VARCHAR2(50) DEFAULT NULL,
    "BOOKEDSEATS" VARCHAR2(500) DEFAULT NULL
);

CREATE OR REPLACE TRIGGER "BUSES_TRG"
BEFORE INSERT ON "BUSES"
FOR EACH ROW
BEGIN
  IF :new."ID" IS NULL THEN
    SELECT "BUSES_SEQ".NEXTVAL INTO :new."ID" FROM DUAL;
  END IF;
END;
/

-- Create BOOKINGS table
CREATE TABLE "BOOKINGS" (
    "ID" NUMBER PRIMARY KEY,
    "USEREMAIL" VARCHAR2(100) NOT NULL,
    "BUSID" NUMBER(10) NOT NULL,
    "BUSNAME" VARCHAR2(100) NOT NULL,
    "FROMDISTRICT" VARCHAR2(100) NOT NULL,
    "TODISTRICT" VARCHAR2(100) NOT NULL,
    "JOURNEYDATE" VARCHAR2(50) NOT NULL,
    "SEATS" VARCHAR2(100) NOT NULL,
    "PAYMENTMETHOD" VARCHAR2(50) NOT NULL,
    "TICKETISSUINGTIME" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "DEPARTURETIME" VARCHAR2(50) DEFAULT NULL,
    "STATUS" VARCHAR2(50) DEFAULT 'Upcoming' NOT NULL
);

CREATE OR REPLACE TRIGGER "BOOKINGS_TRG"
BEFORE INSERT ON "BOOKINGS"
FOR EACH ROW
BEGIN
  IF :new."ID" IS NULL THEN
    SELECT "BOOKINGS_SEQ".NEXTVAL INTO :new."ID" FROM DUAL;
  END IF;
END;
/

-- Create REVIEWS table
CREATE TABLE "REVIEWS" (
    "ID" NUMBER PRIMARY KEY,
    "BOOKINGID" NUMBER(10) NOT NULL,
    "USEREMAIL" VARCHAR2(100) NOT NULL,
    "BUSOPERATOR" VARCHAR2(100) NOT NULL,
    "ROUTE" VARCHAR2(200) NOT NULL,
    "JOURNEYDATE" VARCHAR2(50) NOT NULL,
    "RATING" NUMBER(10) NOT NULL,
    "COMMENT" VARCHAR2(1000) NOT NULL,
    "CREATEDAT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE OR REPLACE TRIGGER "REVIEWS_TRG"
BEFORE INSERT ON "REVIEWS"
FOR EACH ROW
BEGIN
  IF :new."ID" IS NULL THEN
    SELECT "REVIEWS_SEQ".NEXTVAL INTO :new."ID" FROM DUAL;
  END IF;
END;
/

-- Create index on BUSES table
CREATE INDEX "IX_BUSES_FROMTO" ON "BUSES" ("FROMDISTRICT", "TODISTRICT");

-- Seed default notices matching system requirements
INSERT INTO "NOTICES" ("NOTICENUMBER", "TITLE", "CONTENT") VALUES 
('01', 'Refund Policy', 'Eid tickets are non-cancellable, non-transferable, and non-refundable, except where a refund is approved under the applicable refund policy due to operator-cancelled trips.');

INSERT INTO "NOTICES" ("NOTICENUMBER", "TITLE", "CONTENT") VALUES 
('02', 'Eid Period', 'As per Bangladesh Bus Owners Association''s declaration, the Eid trip period will be from 14 May 2026 to 13 June 2026.');

INSERT INTO "NOTICES" ("NOTICENUMBER", "TITLE", "CONTENT") VALUES 
('03', 'Operator Rights', 'Bus operators reserve the right to delay, cancel, reschedule, change bus type, change seats, change routes, or change boarding points due to unavoidable operational reasons.');

INSERT INTO "NOTICES" ("NOTICENUMBER", "TITLE", "CONTENT") VALUES 
('04', 'Reporting Time', 'Passengers must report to the correct boarding point at least 30 minutes before the scheduled departure time. Travello will not be responsible for missed trips, cancellation, rescheduling, or seat reassignment due to late reporting.');

INSERT INTO "NOTICES" ("NOTICENUMBER", "TITLE", "CONTENT") VALUES 
('05', 'Refund Processing', 'If a trip is cancelled by the bus operator and refund is approved, the refundable amount will be credited to the original payment method, bank card or MFS number used for the purchase, within a reasonable timeframe and subject to payment partner policies.');

COMMIT;
